name: Deploy dev on push

on:
  push:
    branches:
      - dev
  workflow_run:  # Écoute la fin de main.yml
    workflows: ["main.yml"]  # Nom exact de ton premier workflow
    branches: [dev]
    types: [completed]

jobs:
  deploy-dev:
    runs-on: [self-hosted, dev]
    if: >-  # Condition : push dev ET main.yml a réussi
      github.event_name == 'push' ||
      (github.event_name == 'workflow_run' && 
       github.event.workflow_run.conclusion == 'success')
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev

      - name: Build Docker images
        run: docker compose build --no-cache

      - name: Deploy & clean
        run: docker compose up -d --remove-orphans --force-recreate
